import { Router } from "express";
import { typeCarDeleteById, typeCarGetRoot, typeCarPostCreate } from "../controllers/setting/typeCarController";
import { brandsCarsDeleteById, brandsCarsGetRoot, brandsCarsPatchById, brandsCarsPostCreate } from "../controllers/setting/brandsCarsController";
import { typeInsuranceDeleteById, typeInsuranceGetById, typeInsuranceGetCmById, typeInsuranceGetCustById, typeInsuranceGetRoot, typeInsuranceGetSById, typeInsuranceGetTypebuy, typeInsurancePostCreate } from "../controllers/setting/typeInsuranceController";
import { insuranceOptionsDeleteById, insuranceOptionsGetTById, insuranceOptionsPatchById, insuranceOptionsPatchRoot, insuranceOptionsPostCreate } from "../controllers/setting/insuranceOptionsController";
import { companyDeleteById, companyGetCustById, companyGetFetch, companyPatchById, companyPostCreate, companyPostEdit } from "../controllers/setting/companyController";
import { versionCarsDeleteById, versionCarsGetRoot, versionCarsPatchById, versionCarsPostCreate } from "../controllers/setting/versionCarsController";
import { usersDeleteById, usersGetAgent, usersGetBuy, usersGetById, usersGetCmn, usersGetOac, usersPostCreate, usersPostEditpass } from "../controllers/setting/usersController";
import { departmentGetById, departmentGetRoot } from "../controllers/setting/departmentController";
import { provinceGetById, provinceGetRoot, provincePatchSectionById } from "../controllers/setting/provinceController";
import { districtGetById, districtGetPvById, districtPatchRoot } from "../controllers/setting/districtController";
import { currencyDeleteById, currencyGetRoot, currencyPostCreate } from "../controllers/setting/currencyController";
import { statusInsuranceGetRoot } from "../controllers/setting/statusInsuranceController";
import { agentSaleDeleteById, agentSaleGetCustById, agentSaleGetOption, agentSaleGetRoot, agentSalePostCreate } from "../controllers/data/agentSaleController";
import { insuranceDeleteBeneById, insuranceDeleteById, insuranceGetById, insuranceGetViewBuyById, insurancePostAddbene, insurancePostContract, insurancePostCreate, insurancePostEditbene, insurancePostMovedata, insurancePostRenew, insurancePostSearch } from "../controllers/data/insuranceController";
import { customBuyerDeleteById, customBuyerGetById, customBuyerGetCmById, customBuyerGetOptionById, customBuyerPostAll, customBuyerPostCreate, customBuyerPostRoot, customBuyerPostSearch } from "../controllers/data/customBuyerController";
import { paysDebtGetContractById, paysDebtPostCreate, paysDebtPostCreateMT, paysDebtPostDelete, paysDebtPostEdit, paysDebtPostReport } from "../controllers/data/paysDebtController";
import { insuranceReturnDeleteById, insuranceReturnGetDelFileById, insuranceReturnGetEditById, insuranceReturnPostCn, insuranceReturnPostCreate, insuranceReturnPostReport, insuranceReturnPostReportPay, insuranceReturnPostRetrun, insuranceReturnPostRetrunEdit, insuranceReturnPostRoot, insuranceReturnPostSearch } from "../controllers/data/insuranceReturnController";
import { upload as uploadFileUpload, uploadFileDeleteById, uploadFilePostCreate, uploadFilePostDelmt } from "../controllers/data/uploadFileController";
import { commissionGetDeleteById, commissionGetPostCreate, commissionGetPostFetch, commissionGetPostSingle, commissionGetPutEdit } from "../controllers/data/commissionGetController";
import { commissionPayDeleteById, commissionPayPostCreate, commissionPayPostFetch, commissionPayPostSingle, commissionPayPutEdit } from "../controllers/data/commissionPayController";
import { insuranceReportGetBeneById, insuranceReportPostAll, insuranceReportPostCars, insuranceReportPostCbuy, insuranceReportPostData, insuranceReportPostHistorybuy, insuranceReportPostMove, insuranceReportPostNotific, insuranceReportPostSearch } from "../controllers/reports/insuranceReportController";
import { insuranceDebtReportGetSum, insuranceDebtReportPostAgent, insuranceDebtReportPostCompany, insuranceDebtReportPostCustomer, insuranceDebtReportPostOac } from "../controllers/reports/insuranceDebtReportController";
import { homeReportGetChartAgentById, homeReportGetChartBuyById, homeReportGetGetChartCnById, homeReportGetGetChartData, homeReportPostBalanch, homeReportPostPaydebt } from "../controllers/reports/homeReportController";
import { historyReportPostCm, historyReportPostRoport } from "../controllers/reports/historyReportController";
import { loginPostCheck } from "../controllers/auth/loginController";

const appRoutes = Router();

appRoutes.post("/typecar/create", typeCarPostCreate);
appRoutes.delete("/typecar/:id", typeCarDeleteById);
appRoutes.get("/typecar", typeCarGetRoot);
appRoutes.post("/brands/create", brandsCarsPostCreate);
appRoutes.delete("/brands/:id", brandsCarsDeleteById);
appRoutes.get("/brands", brandsCarsGetRoot);
appRoutes.patch("/brands/:id", brandsCarsPatchById);
appRoutes.post("/type-ins/create", typeInsurancePostCreate);
appRoutes.delete("/type-ins/:id", typeInsuranceDeleteById);
appRoutes.get("/type-ins", typeInsuranceGetRoot);
appRoutes.get("/type-ins/cust/:id", typeInsuranceGetCustById);
appRoutes.get("/type-ins/cm/:id", typeInsuranceGetCmById);
appRoutes.get("/type-ins/s/:id", typeInsuranceGetSById);
appRoutes.get("/type-ins/typebuy", typeInsuranceGetTypebuy);
appRoutes.get("/type-ins/:id", typeInsuranceGetById);
appRoutes.post("/options/create", insuranceOptionsPostCreate);
appRoutes.delete("/options/:id", insuranceOptionsDeleteById);
appRoutes.patch("/options", insuranceOptionsPatchRoot);
appRoutes.get("/options/t/:id", insuranceOptionsGetTById);
appRoutes.patch("/options/:id", insuranceOptionsPatchById);
appRoutes.post("/company/create", companyPostCreate);
appRoutes.post("/company/edit", companyPostEdit);
appRoutes.delete("/company/:id", companyDeleteById);
appRoutes.get("/company/fetch", companyGetFetch);
appRoutes.get("/company/cust/:id", companyGetCustById);
appRoutes.patch("/company/:id", companyPatchById);
appRoutes.post("/version/create", versionCarsPostCreate);
appRoutes.delete("/version/:id", versionCarsDeleteById);
appRoutes.get("/version", versionCarsGetRoot);
appRoutes.patch("/version/:id", versionCarsPatchById);
appRoutes.post("/user/create", usersPostCreate);
appRoutes.post("/user/editpass", usersPostEditpass);
appRoutes.delete("/user/:id", usersDeleteById);
appRoutes.get("/user/oac", usersGetOac);
appRoutes.get("/user/agent", usersGetAgent);
appRoutes.get("/user/buy", usersGetBuy);
appRoutes.get("/user/cmn", usersGetCmn);
appRoutes.get("/user/:id", usersGetById);
appRoutes.get("/depart", departmentGetRoot);
appRoutes.get("/depart/:id", departmentGetById);
appRoutes.get("/province", provinceGetRoot);
appRoutes.get("/province/:id", provinceGetById);
appRoutes.patch("/province/section/:id", provincePatchSectionById);
appRoutes.patch("/district", districtPatchRoot);
appRoutes.get("/district/:id", districtGetById);
appRoutes.get("/district/pv/:id", districtGetPvById);
appRoutes.post("/currency/create", currencyPostCreate);
appRoutes.delete("/currency/:id", currencyDeleteById);
appRoutes.get("/currency", currencyGetRoot);
appRoutes.get("/status", statusInsuranceGetRoot);
appRoutes.post("/agent/create", agentSalePostCreate);
appRoutes.get("/agent", agentSaleGetRoot);
appRoutes.get("/agent/cust/:id", agentSaleGetCustById);
appRoutes.get("/agent/option", agentSaleGetOption);
appRoutes.delete("/agent/:id", agentSaleDeleteById);
appRoutes.post("/insurance/create", insurancePostCreate);
appRoutes.post("/insurance/renew", insurancePostRenew);
appRoutes.get("/insurance/:id", insuranceGetById);
appRoutes.post("/insurance/search", insurancePostSearch);
appRoutes.post("/insurance/movedata", insurancePostMovedata);
appRoutes.get("/insurance/viewBuy/:id", insuranceGetViewBuyById);
appRoutes.delete("/insurance/:id", insuranceDeleteById);
appRoutes.post("/insurance/addbene", insurancePostAddbene);
appRoutes.post("/insurance/editbene", insurancePostEditbene);
appRoutes.delete("/insurance/bene/:id", insuranceDeleteBeneById);
appRoutes.post("/insurance/contract", insurancePostContract);
appRoutes.post("/custom/create", customBuyerPostCreate);
appRoutes.get("/custom/:id", customBuyerGetById);
appRoutes.get("/custom/option/:id", customBuyerGetOptionById);
appRoutes.post("/custom/all", customBuyerPostAll);
appRoutes.get("/custom/cm/:id", customBuyerGetCmById);
appRoutes.post("/custom", customBuyerPostRoot);
appRoutes.delete("/custom/:id", customBuyerDeleteById);
appRoutes.post("/custom/search", customBuyerPostSearch);
appRoutes.post("/pays/create", paysDebtPostCreate);
appRoutes.post("/pays/edit", paysDebtPostEdit);
appRoutes.post("/pays/delete", paysDebtPostDelete);
appRoutes.post("/pays/createMT", paysDebtPostCreateMT);
appRoutes.post("/pays/report", paysDebtPostReport);
appRoutes.get("/pays/contract/:id", paysDebtGetContractById);
appRoutes.post("/retrun/create", insuranceReturnPostCreate);
appRoutes.post("/retrun/retrun", insuranceReturnPostRetrun);
appRoutes.post("/retrun", insuranceReturnPostRoot);
appRoutes.post("/retrun/report", insuranceReturnPostReport);
appRoutes.delete("/retrun/:id", insuranceReturnDeleteById);
appRoutes.get("/retrun/edit/:id", insuranceReturnGetEditById);
appRoutes.post("/retrun/cn", insuranceReturnPostCn);
appRoutes.post("/retrun/report-pay", insuranceReturnPostReportPay);
appRoutes.post("/retrun/search", insuranceReturnPostSearch);
appRoutes.post("/retrun/retrun-edit", insuranceReturnPostRetrunEdit);
appRoutes.get("/retrun/del-file/:id", insuranceReturnGetDelFileById);
appRoutes.post("/upload/create", uploadFileUpload.array('files'), uploadFilePostCreate);
appRoutes.delete("/upload/:id", uploadFileDeleteById);
appRoutes.post("/upload/delmt", uploadFilePostDelmt);
appRoutes.post("/comisget/create", commissionGetPostCreate);
appRoutes.delete("/comisget/:id", commissionGetDeleteById);
appRoutes.put("/comisget/edit", commissionGetPutEdit);
appRoutes.post("/comisget/single", commissionGetPostSingle);
appRoutes.post("/comisget/fetch", commissionGetPostFetch);
appRoutes.post("/comispay/create", commissionPayPostCreate);
appRoutes.delete("/comispay/:id", commissionPayDeleteById);
appRoutes.put("/comispay/edit", commissionPayPutEdit);
appRoutes.post("/comispay/single", commissionPayPostSingle);
appRoutes.post("/comispay/fetch", commissionPayPostFetch);
appRoutes.post("/report/all", insuranceReportPostAll);
appRoutes.post("/report/cars", insuranceReportPostCars);
appRoutes.post("/report/cbuy", insuranceReportPostCbuy);
appRoutes.post("/report/historybuy", insuranceReportPostHistorybuy);
appRoutes.post("/report/data", insuranceReportPostData);
appRoutes.post("/report/notific", insuranceReportPostNotific);
appRoutes.post("/report/move", insuranceReportPostMove);
appRoutes.get("/report/bene/:id", insuranceReportGetBeneById);
appRoutes.post("/report/search", insuranceReportPostSearch);
appRoutes.post("/debt/company", insuranceDebtReportPostCompany);
appRoutes.post("/debt/agent", insuranceDebtReportPostAgent);
appRoutes.post("/debt/customer", insuranceDebtReportPostCustomer);
appRoutes.post("/debt/oac", insuranceDebtReportPostOac);
appRoutes.get("/debt/sum", insuranceDebtReportGetSum);
appRoutes.post("/home/balanch", homeReportPostBalanch);
appRoutes.get("/home/getChartData", homeReportGetGetChartData);
appRoutes.get("/home/getChartCn/:id", homeReportGetGetChartCnById);
appRoutes.get("/home/chartAgent/:id", homeReportGetChartAgentById);
appRoutes.get("/home/chartBuy/:id", homeReportGetChartBuyById);
appRoutes.post("/home/paydebt", homeReportPostPaydebt);
appRoutes.post("/history/cm", historyReportPostCm);
appRoutes.post("/history/roport", historyReportPostRoport);
appRoutes.post("/login/check", loginPostCheck);

export default appRoutes;
